const express = require('express')
const router = express.Router()
const { signIn, logout, signup } = require('../controllers/field-agent/fieldAgentSignin')
const { forgotPassword, updatePassword, confirmPasswordVerificationToken, resetPasswordVerificationToken } = require('../controllers/field-agent/forgotPassword')
const authenticateFieldAgent = require('../middleware/authenticateFieldAgent')
const { addPropertyDealer, propertyDealerEmailExists, propertyDealerContactNumberExists, propertyDealerGstNumberExists } = require('../controllers/field-agent/addPropertyDealer')
const { uploadImage } = require('../controllers/uploadImage')

router.post('/signIn', signIn)
router.patch('/logout', authenticateFieldAgent, logout)
router.post('/signUp', signup)
router.patch('/forgotPassword', forgotPassword)
router.patch('/updatePassword', updatePassword)
router.post('/confirmPasswordVerificationToken', confirmPasswordVerificationToken)
router.patch('/resetPasswordVerificationToken', resetPasswordVerificationToken)
router.post('/addPropertyDealer', authenticateFieldAgent, addPropertyDealer)
router.post('/uploadPropertyDealerImage', uploadImage)
router.get('/propertyDealerEmailExists', propertyDealerEmailExists)
router.get('/propertyDealerContactNumberExists', propertyDealerContactNumberExists)
router.get('/propertyDealerGstNumberExists', propertyDealerGstNumberExists)

module.exports = router